[package]
name = "hello"
version = "1.0.0"
authors = ["Movelazy"]

[addresses]
hello_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" } 